services:
  - type: web
    name: video-annotator-demo
    env: docker
    region: oregon         # or your region
    branch: main
    dockerfilePath: FreeFuse_Internship_Project/video-annotator-demo/Dockerfile